### PR TITLE
Site Condition refactor

### PR DESCRIPTION
**Pull request by YazidZidane**
- Solved problem that state and map state not auto filled if import data from csv.
- Refactored Site Condition to reduce multiple api call and redux actions.
- Updated file structure.

### CODE REVIEW

**Comment by mikahpinegar** [comment]
i'm getting this error on lots of crops 

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
    at updateSeeds (index.js:124:1)
```

**Comment by mikahpinegar** [comment]
and this error on some others 
```
Cannot read properties of undefined (reading 'values')
TypeError: Cannot read properties of undefined (reading 'values')
    at updateSeeds (http://localhost:3001/static/js/bundle.js:11936:121)
```

**Comment by YazidZidane** [comment]
> i'm getting this error on lots of crops
> 
> ```
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
>     at updateSeeds (index.js:124:1)
> ```



> and this error on some others
> 
> ```
> index.js:104 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'values')
>     at updateSeeds (index.js:104:1)
> ```

Are these errors only appears for Indiana? I guess these are some errors with the api and is not resolved in this pr.

**Comment by YazidZidane** [comment]
> i'm getting this error on lots of crops
> 
> ```
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
>     at updateSeeds (index.js:124:1)
> ```



> and this error on some others
> 
> ```
> index.js:104 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'values')
>     at updateSeeds (index.js:104:1)
> ```

These problems should be solved with the new commit. Now only Soybean in NECCC would cause errors because it doesn't have a Coefficients property.

**Comment by mikahpinegar** [comment]
importing from csv is giving me this error 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at index.js:67:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)
    at commitRootImpl (react-dom.development.js:26935:1)
    at commitRoot (react-dom.development.js:26682:1)
```

**Comment by mikahpinegar** [comment]
i just got this error when going to the confirm plan step 
```
soilDrainages.join is not a function
TypeError: soilDrainages.join is not a function
    at calculateSoilDrainage (http://localhost:3001/static/js/bundle.js:12891:27)
    at http://localhost:3001/static/js/bundle.js:12923:32
    at Array.map (<anonymous>)
    at generateNRCSStandards (http://localhost:3001/static/js/bundle.js:12919:17)
    at http://localhost:3001/static/js/bundle.js:4693:92
    at commitHookEffectListMount (http://localhost:3001/static/js/bundle.js:137972:30)
    at commitPassiveMountOnFiber (http://localhost:3001/static/js/bundle.js:139465:17)
    at commitPassiveMountEffects_complete (http://localhost:3001/static/js/bundle.js:139437:13)
    at commitPassiveMountEffects_begin (http://localhost:3001/static/js/bundle.js:139427:11)
    at commitPassiveMountEffects (http://localhost:3001/static/js/bundle.js:139417:7)
```

**Comment by YazidZidane** [comment]
> i just got this error when going to the confirm plan step for indiana
> 
> ```
> soilDrainages.join is not a function
> TypeError: soilDrainages.join is not a function
>     at calculateSoilDrainage (http://localhost:3001/static/js/bundle.js:12891:27)
>     at http://localhost:3001/static/js/bundle.js:12923:32
>     at Array.map (<anonymous>)
>     at generateNRCSStandards (http://localhost:3001/static/js/bundle.js:12919:17)
>     at http://localhost:3001/static/js/bundle.js:4693:92
>     at commitHookEffectListMount (http://localhost:3001/static/js/bundle.js:137972:30)
>     at commitPassiveMountOnFiber (http://localhost:3001/static/js/bundle.js:139465:17)
>     at commitPassiveMountEffects_complete (http://localhost:3001/static/js/bundle.js:139437:13)
>     at commitPassiveMountEffects_begin (http://localhost:3001/static/js/bundle.js:139427:11)
>     at commitPassiveMountEffects (http://localhost:3001/static/js/bundle.js:139417:7)
> ```

Which plants are you selected?

**Comment by mikahpinegar** [comment]
all 3 brassicas

**Comment by YazidZidane** [comment]
> i just got this error when going to the confirm plan step for indiana
> 
> ```
> soilDrainages.join is not a function
> TypeError: soilDrainages.join is not a function
>     at calculateSoilDrainage (http://localhost:3001/static/js/bundle.js:12891:27)
>     at http://localhost:3001/static/js/bundle.js:12923:32
>     at Array.map (<anonymous>)
>     at generateNRCSStandards (http://localhost:3001/static/js/bundle.js:12919:17)
>     at http://localhost:3001/static/js/bundle.js:4693:92
>     at commitHookEffectListMount (http://localhost:3001/static/js/bundle.js:137972:30)
>     at commitPassiveMountOnFiber (http://localhost:3001/static/js/bundle.js:139465:17)
>     at commitPassiveMountEffects_complete (http://localhost:3001/static/js/bundle.js:139437:13)
>     at commitPassiveMountEffects_begin (http://localhost:3001/static/js/bundle.js:139427:11)
>     at commitPassiveMountEffects (http://localhost:3001/static/js/bundle.js:139417:7)
> ```

I have pushed a new commit which should solve this problem.

**Review by mikahpinegar — APPROVED** [review]

**Pull request merged**
